# Write your MySQL query statement below
(SELECT U.NAME RESULTS
FROM MOVIERATING MR
JOIN USERS U ON MR.USER_ID = U.USER_ID
GROUP BY U.USER_ID
ORDER BY COUNT(*) DESC, U.NAME
LIMIT 1)
UNION ALL
(SELECT M.TITLE RESULTS
FROM MOVIERATING MR
JOIN MOVIES M ON MR.MOVIE_ID = M.MOVIE_ID
WHERE '2020-02-01' <= MR.CREATED_AT AND MR.CREATED_AT < '2020-03-01'
GROUP BY M.MOVIE_ID
ORDER BY AVG(MR.RATING) DESC, M.TITLE
LIMIT 1)