# Write your MySQL query statement below
SELECT E1.EMPLOYEE_ID, E1.NAME NAME, COUNT(E1.EMPLOYEE_ID) REPORTS_COUNT, ROUND(AVG(E2.AGE)) AVERAGE_AGE
FROM EMPLOYEES E1
JOIN EMPLOYEES E2 ON E2.REPORTS_TO = E1.EMPLOYEE_ID
GROUP BY E1.EMPLOYEE_ID
ORDER BY E1.EMPLOYEE_ID