# Write your MySQL query statement below
SELECT Q.QUERY_NAME, ROUND(AVG(Q.RATING / Q.POSITION), 2) QUALITY, ROUND((Q2.C / COUNT(*)) * 100, 2) POOR_QUERY_PERCENTAGE
FROM QUERIES Q
JOIN (SELECT Q.QUERY_NAME, COUNT(*) C
FROM QUERIES Q
WHERE Q.RATING < 3
GROUP BY Q.QUERY_NAME) Q2 ON Q.QUERY_NAME = Q2.QUERY_NAME 
GROUP BY Q.QUERY_NAME