# Write your MySQL query statement below
SELECT 
    DATE_FORMAT(TRANS_DATE, "%Y-%m") MONTH, 
    COUNTRY, 
    COUNT(*) TRANS_COUNT, 
    SUM(CASE WHEN STATE = 'APPROVED' THEN 1 ELSE 0 END) APPROVED_COUNT,
    SUM(AMOUNT) TRANS_TOTAL_AMOUNT,
    SUM(CASE WHEN STATE = 'APPROVED' THEN AMOUNT ELSE 0 END) APPROVED_TOTAL_AMOUNT
FROM TRANSACTIONS
GROUP BY DATE_FORMAT(TRANS_DATE, "%Y-%m"), COUNTRY