# Write your MySQL query statement below
SELECT ACTIVITY_DATE DAY, COUNT(DISTINCT USER_ID) ACTIVE_USERS
FROM ACTIVITY
WHERE DATE_SUB("2019-07-27", INTERVAL 30 DAY) < ACTIVITY_DATE AND ACTIVITY_DATE <= "2019-07-27"
GROUP BY ACTIVITY_DATE