# Write your MySQL query statement below
SELECT ACTIVITY_DATE DAY, COUNT(DISTINCT USER_ID) ACTIVE_USERS
FROM ACTIVITY
WHERE ACTIVITY_DATE BETWEEN DATE_SUB("2019-07-28", INTERVAL 30 DAY) AND "2019-07-27"
GROUP BY ACTIVITY_DATE