# Write your MySQL query statement below
SELECT R.CONTEST_ID, ROUND((COUNT(*) / (SELECT COUNT(*) FROM USERS)) * 100, 2) PERCENTAGE
FROM USERS U
JOIN REGISTER R ON U.USER_ID = R.USER_ID
GROUP BY R.CONTEST_ID
ORDER BY PERCENTAGE DESC, R.CONTEST_ID