# Write your MySQL query statement below
SELECT S.PRODUCT_ID, S.YEAR FIRST_YEAR, S.QUANTITY, S.PRICE
FROM SALES S
JOIN (SELECT PRODUCT_ID, MIN(YEAR) FIRST_YEAR FROM SALES GROUP BY PRODUCT_ID) YEAR
ON S.PRODUCT_ID = YEAR.PRODUCT_ID AND S.YEAR = YEAR.FIRST_YEAR