# Write your MySQL query statement below
SELECT E1.EMPLOYEE_ID, IFNULL(E2.DEPARTMENT_ID, E1.DEPARTMENT_ID) DEPARTMENT_ID
FROM EMPLOYEE E1
LEFT JOIN EMPLOYEE E2 ON E1.EMPLOYEE_ID = E2.EMPLOYEE_ID AND E2.PRIMARY_FLAG = "Y"
GROUP BY E1.EMPLOYEE_ID