-- # Write your MySQL query statement below
SELECT ROUND(COUNT(*) / (SELECT COUNT(DISTINCT PLAYER_ID) FROM ACTIVITY), 2) FRACTION
FROM ACTIVITY A
JOIN (SELECT PLAYER_ID, MIN(EVENT_DATE) FIRST_DATE FROM ACTIVITY GROUP BY PLAYER_ID) F ON A.PLAYER_ID = F.PLAYER_ID
WHERE A.EVENT_DATE = DATE_ADD(F.FIRST_DATE, INTERVAL 1 DAY)