# Write your MySQL query statement below
SELECT A_S.MACHINE_ID, ROUND(AVG(A_E.TIMESTAMP - A_S.TIMESTAMP), 3) PROCESSING_TIME
FROM ACTIVITY A_S
JOIN ACTIVITY A_E ON A_S.MACHINE_ID = A_E.MACHINE_ID AND A_S.PROCESS_ID = A_E.PROCESS_ID 
WHERE A_S.ACTIVITY_TYPE = "START" AND A_E.ACTIVITY_TYPE = "END"
GROUP BY A_S.MACHINE_ID