# Write your MySQL query statement below
SELECT S.USER_ID, ROUND(IFNULL(SUM(C.ACTION = "confirmed") / COUNT(C.ACTION), 0), 2) CONFIRMATION_RATE
FROM SIGNUPS S
LEFT JOIN CONFIRMATIONS C ON S.USER_ID = C.USER_ID
GROUP BY S.USER_ID