# Write your MySQL query statement below
SELECT ROUND(AVG(D.ORDER_DATE >= D.CUSTOMER_PREF_DELIVERY_DATE), 4) * 100 IMMEDIATE_PERCENTAGE
FROM DELIVERY D
WHERE ORDER_DATE = (
    SELECT MIN(ORDER_DATE)
    FROM DELIVERY
    WHERE CUSTOMER_ID = D.CUSTOMER_ID
);
