# Write your MySQL query statement below
SELECT P.PRODUCT_ID,
CASE 
    WHEN COUNT(*) != 0 THEN ROUND(SUM(P.PRICE * U.UNITS) / SUM(U.UNITS), 2)
    ELSE 0
END AVERAGE_PRICE
FROM PRICES P
JOIN UNITSSOLD U ON U.PURCHASE_DATE BETWEEN P.START_DATE AND P.END_DATE AND P.PRODUCT_ID = U.PRODUCT_ID
GROUP BY P.PRODUCT_ID
ORDER BY P.PRODUCT_ID