# Write your MySQL query statement below
SELECT ST.STUDENT_ID, ST.STUDENT_NAME, SUB.SUBJECT_NAME, COUNT(E.STUDENT_ID) ATTENDED_EXAMS
FROM STUDENTS ST
CROSS JOIN SUBJECTS SUB
LEFT JOIN EXAMINATIONS E ON ST.STUDENT_ID = E.STUDENT_ID AND SUB.SUBJECT_NAME = E.SUBJECT_NAME
GROUP BY ST.STUDENT_ID, SUB.SUBJECT_NAME
ORDER BY ST.STUDENT_ID, SUB.SUBJECT_NAME